alias eyewitness='python3 ~/tools/EyeWitness/Python/EyeWitness'
alias mot='nsxiv ~/hack/.mot/pics/* & disown; mpv ~/hack/.mot/vids/* & disown; exit'
alias v='vim'
alias sv='sudo vim'
alias learn='cat ~/hack/learn'
alias sa='sudo apt'
alias shutdown='sudo systemctl poweroff'
alias amass='~/tools/amass_Linux_amd64/amass'
alias ysoserial='java --add-opens java.base/sun.reflect.annotation=ALL-UNNAMED -jar ~/tools/ysoserial-all.jar'
alias bg='ls ~/.backgrounds/ | dmenu -c -l 20 | xargs -I{} feh --bg-fill ~/.backgrounds/{}'
alias c='clear'
alias pushmodules='rsync /home/benny/recon/modules -uvrp root@dendy.xyz:/root/recon'
alias githubtoken='cat .sensitive/github-token | xclip'
